style: github
template: CHANGELOG.tpl.md
info:
  title: "CHANGE LOG"
  repository_url: https://github.com/StuartApp/Experiment-Analysis-Tool
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
