---
name: 🔄 Test dependency updates

on:
  #schedule:
  #  - cron: "0 5 * * 1"

  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Update dependencies
        run: |
            make update-lock-requirements
            echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update pinned versions on ${{ env.DATE }}"
          branch: "update/update-pinned-versions-${{ env.DATE }}"
          base: ${{ github.ref_name }}
        # It doesn't work really, because currently the new PR doesn't trigger
        # the checks for PRs if it uses the GITHUB_TOKEN. More info on the "Note:" here
        # https://github.com/marketplace/actions/create-pull-request#action-inputs
        # and here
        # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
