---
name: 🚀 Build and publish

on:
  push:
    tags:
      - '*'
    branches:
      - snapshot/*
  workflow_call:
    inputs:
      git-ref:
        description: "git tag, branch or commit to use"
        type: string
        required: true


concurrency:
  group: deploy

jobs:
  build-and-publish-package:
    name: "Publish python package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "${{ inputs.git-ref || github.head_ref }}"
          fetch-depth: 0
          token: ${{ secrets.GHA_TRIGGER_TOKEN }}

      - name: Setup UV & python
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
          python-version: "3.12"

      - name: Build Package
        run: |
          make build

      - name: Publish Package
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
        run: |
          echo "Nexus user ${NEXUS_USER}"
          make publish
